FROM python:3.8-slim

# Copy the Python script into the container
COPY addition.py /app/addition.py

# Set the working directory
WORKDIR /app

# Command to run your script
CMD ["python", "addition_num.py"]