FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the Python script into the container
COPY addition_num.py /app/addition_num.py

# Command to run your script
CMD ["python", "addition_num.py"]