version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    networks:
      - my-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - my-network

networks:
  my-network:
    driver: bridge